### PR TITLE
Optimize wallet components

### PR DESCRIPTION
**Pull request by lisandroiraguen**
it needs some final adjustments, but you can see how is it going on

### CODE REVIEW

**Comment by nothingalike** [comment]
@lisandroiraguen alright everything is looking really good. i know you said its still a work in progress, but here are some things i've noticed.
- When minting tokens, the form doesn't spin on submit.
- The minting token form also doesn't return you to the Transactions tab when successful.
- When i click on a transaction hash, it doesnt take me to the cardano explorer

**Comment by lisandroiraguen** [comment]
Mint token wasn't originally on the code optimization but now I am moving it on, sorry, I didn't clarify this, it is the last step

When i click on a transaction hash, it doesn't take me to the cardano explorer
let me see this, I think it is a bug

**Comment by lisandroiraguen** [comment]
@nothingalike @rcmorano you can test it now 🗡️ let me know If you find any bug

**Comment by nothingalike** [comment]
> @nothingalike @rcmorano you can test it now 🗡️ let me know If you find any bug

Is this newer?

**Comment by lisandroiraguen** [comment]
mmm it depends 🐙 it is not soo new

**Comment by rcmorano** [comment]
I've just downloaded latest artifact from GH actions and everything (create, send, receive, txs list...) but minting works.

I'm not sure if this branch started from an inconsistent `main` branch, anyways, I think it's time to create a `develop` branch where we can merge this and keep working w/o worrying to break things :)

**Comment by rcmorano** [comment]
I'm merging this into develop and will try to figure out from there :)

Great job @lisandroiraguen, thanks :D!

**Pull request merged**
